apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=   # "postgres" en base64
  SPRING_DATASOURCE_PASSWORD: MTIzNA==       # "1234" en base64
